# Generated by Django 4.2 on 2025-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_job_order_source_job_estimated_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='inspection_images',
            field=models.ImageField(blank=True, null=True, upload_to='inspection_images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
